name: Deploy
on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Deploy Discord to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: ${{ secrets.DENO_DEPLOY_PROJECT_DISCORD }}
          entrypoint: "./src/main.ts"
          root: "discord"

      - name: Deploy API to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: ${{ secrets.DENO_DEPLOY_PROJECT_API }}
          entrypoint: "./src/main.ts"
          root: "api"
